package com.simplemobiletools.calculator.helpers

const val DIGIT = "digit"
const val EQUALS = "equals"
const val PLUS = "plus"
const val MINUS = "minus"
const val MULTIPLY = "multiply"
const val DIVIDE = "divide"
const val PERCENT = "percent"
const val POWER = "power"
const val ROOT = "root"
const val DECIMAL = "decimal"
const val CLEAR = "clear"
const val RESET = "reset"
const val FACTORIAL = "factorial"

const val NAN = "NaN"
const val ZERO = "zero"
const val ONE = "one"
const val TWO = "two"
const val THREE = "three"
const val FOUR = "four"
const val FIVE = "five"
const val SIX = "six"
const val SEVEN = "seven"
const val EIGHT = "eight"
const val NINE = "nine"

const val PLUS_SIGN = "+"
const val MINUS_SIGN = "-"
const val DIVIDE_SIGN = "/"
const val MULTIPLY_SIGN = "*"
const val PERCENT_SIGN = "%"
const val POWER_SIGN = "^"
const val ROOT_SIGN = "√"
const val FACTORIAL_SIGN = "!"
const val EQUALS_SIGN = "="
const val BLANK_SIGN = ""
